if get_option('installed_tests')
  install_data(
    'primary-a.gpg',
    'primary-a.sec.gpg',
    'primary-a-newsubkey.gpg',
    'primary-a-newsubkey.sec.gpg',
    'primary-a-extended.gpg',
    'primary-a-revoked.gpg',
    'primary-a-revokedsubkey.gpg',
    'primary-b-old.gpg',
    'primary-b-old.sec.gpg',
    'primary-b-new.sec.gpg',
    'primary-b-new-crosssigned.gpg',
    'primary-b-new-unsigned.gpg',
    'primary-b-new-selfsigned.gpg',
    'unrelated.gpg',
    'key-ids.txt',
    'README',
    install_dir : installed_tests_dir / 'test-keyring3',
  )
endif
